### ISSUE TITLE
[BUG] Bug because of failed mail service authentication

### ISSUE THREAD

**Issue by BelisAliosmanova** [Gin-n-Tonicc/Cool-School#57]
**Describe the bug**
There is still a problem in the admin page, specifically the blog table. I can edit the blog if the enabled field is false but it is true it gives me an internal server error. I guess there is a problem with the json sent. Take a look please!

**Screenshots**
![image](https://github.com/Gin-n-Tonicc/Cool-School/assets/107267662/a230c1e1-b2f1-44be-b75c-f9fd606cb67e)
![image](https://github.com/Gin-n-Tonicc/Cool-School/assets/107267662/30dee0a0-8356-40ed-87c4-cf34bd1285f4)

**Additional information**
You can also see that I found and fixed a bug related to this issue in the backend. Due to migration and the mismatch between is_deleted and deleted field names - there were two of them. I am not sure but maybe this can help you find and fix the issue

**Comment by stefan-petrov1** [comment]
Turns out the bug is because of a failed authentication with the email service so I am transfering this issue to you.
